### PR TITLE
Wipe login data

### PR DESCRIPTION
**Pull request by tijno**
This is the PR as per issue #34 

It will clear login info from local storage for all logged in accounts after the user enters a confirmation sentence.

cc @HPaulson

### CODE REVIEW

**Review by HPaulson — APPROVED** [review]
After a quick read of the changes Everything LGTM -- Note though that I'm able to test this locally (as I broke my machine 😬), however I assume you've done so already based on the gif provided in #34.

This doesn't solve the major security concerns which Identity presents, but small additions like this definitely make things a bit easier for the end user. Thanks for the PR!

**Comment by tijno** [comment]
anything else needed in this @maebeam @lazynina 

bunch of people got hacked yesterday due to using extensions and having old accounts logged in. 

not being able to clear local storage easily makes this worse when it happens.

**Comment by maebeam** [comment]
@tijno I'd like to make this a separate component e.g. /logout

Which extensions were compromised?

**Comment by tijno** [comment]
ok will make it separate component.

not sure which ones - @HPaulson looked into that side of the hacked accounts. I could see about 20 likely affected.

**Comment by maebeam** [comment]
thank you!

**Comment by iPaulPro** [comment]
Has anyone provided any proof or identified specific extensions? Seemed like some opportunist FUD to me.

"Someone sent all my CLOUT to an anon address." Please donate. 😂

**Comment by Harman36** [comment]
> Has anyone provided any proof or identified specific extensions? Seemed like some opportunist FUD to me.
> 
> "Someone sent all my CLOUT to an anon address." Please donate. 😂

I had so much loosing money then asking people in discord to help. Its laugh for you because you are not a from third world country. Laughing off people losses, what a shame. And mentioning as I asking for something that wasn't mine.

**Comment by maebeam** [comment]
@tijno if you have some time I'd love to get this merged

**Comment by tijno** [comment]
ill do my best this weekend. 

> I'd like to make this a separate component e.g. /logout

time to learn some angular.

**Comment by akutch** [comment]
I might have time to split this out into a separate component this afternoon. I'll post here before I do just in case you get to it first @tijno

**Comment by tijno** [comment]
earliest i will get to it is sunday

**Comment by akutch** [comment]
@tijno ok I'm starting it today 🙂 I'll see how far I can get. 

Couple clarifying questions – 

1. The work left is just a matter of splitting the 'clear' logic into a separate component (e.g. `clear-account`), right? 
2. Are we thinking this is a separate route as well or just part of log-in?

**Comment by tijno** [comment]
@akutch 

yes separate component

and i think separate route too as "signup" for example from memory is a separate route too. So keep consistent with that.

**Comment by akutch** [comment]
The changes are ready for review here: https://github.com/bitclout/identity/pull/51

**Comment by tijno** [comment]
included in PR mentioned above by @akutch so closing this one.

**Pull request closed without merging**
